@RealEstate_Api_HostAddress = https://localhost:7180




### LOGIN - SUCCESS
POST {{RealEstate_Api_HostAddress}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "test@test.com",
  "password": "123456"
}

###

### LOGIN - FAIL - WRONG PASSWORD
POST {{RealEstate_Api_HostAddress}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "test@test.com",
  "password": "000000"
}

###

### LOGIN - FAIL - MISSING FIELDS
POST {{RealEstate_Api_HostAddress}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "",
  "password": ""
}

###

### LOGIN - FAIL - NULL BODY
POST {{RealEstate_Api_HostAddress}}/api/auth/login
Accept: application/json
Content-Type: application/json

### LOGOUT - SUCCESS
POST {{RealEstate_Api_HostAddress}}/api/Auth/logout
Accept: application/json
